search: search.c
	gcc search.c -lcs50 -o search

search2: search2.c
	gcc search2.c -lcs50 -o search2

phonebook: phonebook.c
	gcc phonebook.c -lcs50 -o phonebook

phonebook2: phonebook2.c
	gcc phonebook2.c -lcs50 -o phonebook2