scores: scores.c
	gcc scores.c -lcs50 -o scores

length: length.c
	gcc length.c -lcs50 -o length

string: string.c
	gcc string.c -lcs50 -o string

uppercase: uppercase.c
	gcc uppercase.c -lcs50 -o uppercase